### ISSUE TITLE
Imprecise Cannon movement with Sequenced Gearshift

### ISSUE THREAD

**Issue by Pecant-Pie** [Cannoneers-of-Create/CreateBigCannons#462]
When moving a cannon using the cannon mount or yaw controller, the RPM has a significant effect on the actual degrees moved, even when a sequenced gearshift set to 90 degrees is used in all cases. 

Specifically, inputting 90 degrees at 8 RPM moves the cannon 12 degrees, 16 RPM moves the cannon 12.6 degrees, but at 32 RPM it moves 14.4 degrees.

This factor is also different depending on the degrees moved. 45 degrees at 8 RPM moves the cannon 6.3 degrees, instead of the 6 I would expect.

This makes it very hard to use the Sequenced Gearshift CC: Tweaked peripheral implementation to aim cannons. If this is unintended behavior I would greatly appreciate a fix.

**Comment by rbasamoyai** [comment]
Should have already been addressed here: https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/420

**Comment by anticitizn** [comment]
Hello @rbasamoyai, this issue still persists for yaw controllers on Fabric 5.5.1 - at 1 RPM sequenced gearshifts are nearly accurate, but get increasingly more inaccurate as RPM increases. Cannon controllers (pitch) work fine. 

Also there seems to be a 1/8 reducing ratio which I suppose is intentional to allow more precise aiming (so a sequenced gearshift set to 1 degree only rotates the cannon 0.125 degrees), but just making sure. Wouldn't a ratio of 1/10 be slightly nicer?

Examples with yaw and pitch sequenced gearshifts set to 8 degrees and triggered only once

1 RPM:
![image](https://github.com/user-attachments/assets/760bff74-bd57-4732-9089-22ab57c27a18)

256 RPM:
![image](https://github.com/user-attachments/assets/490307d6-451a-4395-8d02-1006c96ed064)

**Comment by rbasamoyai** [comment]
Will check later.

**Comment by anticitizn** [comment]
Hello again, I did some more testing on 0.5.2 and if I break the cannon mount, yaw controller and cannon then replace them the issue usually goes away, so it's not that critical. I can't find out how to reproduce it, it just happens occasionally.
